import { describe, expect, it } from "vitest";

import type { Project } from "../model/project";
import type { ProjectWeightModel } from "../weight/build-project-weight-model";
import { buildOperationalTaskViews, calculateTopImpactPercent } from "./build-operational-task-views";

function createProject(): Project {
  return {
    id: "p1",
    name: "Projeto operacional",
    tasks: [
      {
        id: "late-task",
        name: "Atrasada",
        startDate: "2026-02-20T08:00:00",
        endDate: "2026-03-05T17:00:00",
        percentComplete: 20,
        physicalPercentComplete: 0,
        actualStartDate: "2026-02-22T08:00:00",
        actualEndDate: "",
        actualDurationHours: 0,
        actualWorkHours: 0,
        remainingWorkHours: 0,
        baselineStartDate: "2026-02-20T08:00:00",
        baselineEndDate: "2026-03-01T17:00:00",
        baselineDurationHours: 40,
        resumeDate: "",
        stopDate: "",
        duration: 40,
        outlineLevel: 2,
        outlineNumber: "1.1",
        isSummary: false,
        resourceIds: [],
      },
      {
        id: "current-task",
        name: "Em execucao",
        startDate: "2026-03-20T08:00:00",
        endDate: "2026-04-02T17:00:00",
        percentComplete: 45,
        physicalPercentComplete: 0,
        actualStartDate: "2026-03-21T08:00:00",
        actualEndDate: "",
        actualDurationHours: 0,
        actualWorkHours: 0,
        remainingWorkHours: 0,
        baselineStartDate: "2026-03-18T08:00:00",
        baselineEndDate: "2026-03-30T17:00:00",
        baselineDurationHours: 40,
        resumeDate: "",
        stopDate: "",
        duration: 40,
        outlineLevel: 2,
        outlineNumber: "1.2",
        isSummary: false,
        resourceIds: [],
      },
      {
        id: "recent-task",
        name: "Concluida recente",
        startDate: "2026-03-10T08:00:00",
        endDate: "2026-03-18T17:00:00",
        percentComplete: 100,
        physicalPercentComplete: 0,
        actualStartDate: "2026-03-11T08:00:00",
        actualEndDate: "2026-03-22T17:00:00",
        actualDurationHours: 0,
        actualWorkHours: 0,
        remainingWorkHours: 0,
        baselineStartDate: "2026-03-10T08:00:00",
        baselineEndDate: "2026-03-18T17:00:00",
        baselineDurationHours: 24,
        resumeDate: "",
        stopDate: "",
        duration: 24,
        outlineLevel: 2,
        outlineNumber: "1.3",
        isSummary: false,
        resourceIds: [],
      },
      {
        id: "soon-task",
        name: "Comeca em breve",
        startDate: "2026-04-05T08:00:00",
        endDate: "2026-04-20T17:00:00",
        percentComplete: 0,
        physicalPercentComplete: 0,
        actualStartDate: "",
        actualEndDate: "",
        actualDurationHours: 0,
        actualWorkHours: 0,
        remainingWorkHours: 0,
        baselineStartDate: "2026-04-03T08:00:00",
        baselineEndDate: "2026-04-18T17:00:00",
        baselineDurationHours: 32,
        resumeDate: "",
        stopDate: "",
        duration: 32,
        outlineLevel: 2,
        outlineNumber: "1.4",
        isSummary: false,
        resourceIds: [],
      },
      {
        id: "next-front-task",
        name: "Mecanica inicial",
        startDate: "2026-04-03T08:00:00",
        endDate: "2026-04-16T17:00:00",
        percentComplete: 0,
        physicalPercentComplete: 0,
        actualStartDate: "",
        actualEndDate: "",
        actualDurationHours: 0,
        actualWorkHours: 0,
        remainingWorkHours: 0,
        baselineStartDate: "2026-04-01T08:00:00",
        baselineEndDate: "2026-04-14T17:00:00",
        baselineDurationHours: 32,
        resumeDate: "",
        stopDate: "",
        duration: 32,
        outlineLevel: 2,
        outlineNumber: "2.1",
        isSummary: false,
        resourceIds: [],
      },
      {
        id: "future-task",
        name: "Futuro distante",
        startDate: "2026-05-20T08:00:00",
        endDate: "2026-06-10T17:00:00",
        percentComplete: 0,
        physicalPercentComplete: 0,
        actualStartDate: "",
        actualEndDate: "",
        actualDurationHours: 0,
        actualWorkHours: 0,
        remainingWorkHours: 0,
        baselineStartDate: "2026-05-20T08:00:00",
        baselineEndDate: "2026-06-10T17:00:00",
        baselineDurationHours: 80,
        resumeDate: "",
        stopDate: "",
        duration: 80,
        outlineLevel: 2,
        outlineNumber: "1.5",
        isSummary: false,
        resourceIds: [],
      },
      {
        id: "far-front-near-task",
        name: "Teste precoce",
        startDate: "2026-04-04T08:00:00",
        endDate: "2026-04-09T17:00:00",
        percentComplete: 0,
        physicalPercentComplete: 0,
        actualStartDate: "",
        actualEndDate: "",
        actualDurationHours: 0,
        actualWorkHours: 0,
        remainingWorkHours: 0,
        baselineStartDate: "2026-04-04T08:00:00",
        baselineEndDate: "2026-04-09T17:00:00",
        baselineDurationHours: 16,
        resumeDate: "",
        stopDate: "",
        duration: 16,
        outlineLevel: 2,
        outlineNumber: "4.1",
        isSummary: false,
        resourceIds: [],
      },
      {
        id: "old-complete-task",
        name: "Concluida antiga",
        startDate: "2026-01-05T08:00:00",
        endDate: "2026-01-20T17:00:00",
        percentComplete: 100,
        physicalPercentComplete: 0,
        actualStartDate: "2026-01-05T08:00:00",
        actualEndDate: "2026-01-20T17:00:00",
        actualDurationHours: 0,
        actualWorkHours: 0,
        remainingWorkHours: 0,
        baselineStartDate: "2026-01-05T08:00:00",
        baselineEndDate: "2026-01-20T17:00:00",
        baselineDurationHours: 32,
        resumeDate: "",
        stopDate: "",
        duration: 32,
        outlineLevel: 2,
        outlineNumber: "1.6",
        isSummary: false,
        resourceIds: [],
      },
    ],
    resources: [],
    dependencies: [],
  };
}

function createWeightModel(): ProjectWeightModel {
  return {
    normalizedProjectValue: 1_000_000,
    totalEarnedNormalizedValue: 0,
    totalRemainingNormalizedValue: 0,
    progressWeightedPercent: 0,
    progressSourceCoverage: {
      tasksUsingPercentComplete: 0,
      tasksUsingPhysicalPercentComplete: 0,
      tasksConsideredCompletedByActualEndDate: 0,
      tasksWithoutProgressData: 0,
    },
    taskWeights: [
      {
        taskId: "late-task",
        taskName: "Atrasada",
        outlineNumber: "1.1",
        disciplineName: "Civil",
        progressPercentUsed: 20,
        progressSource: "percentComplete",
        normalizedValue: 200_000,
        normalizedWeightPercent: 20,
        earnedNormalizedValue: 40_000,
        remainingNormalizedValue: 160_000,
      },
      {
        taskId: "current-task",
        taskName: "Em execucao",
        outlineNumber: "1.2",
        disciplineName: "Civil",
        progressPercentUsed: 45,
        progressSource: "percentComplete",
        normalizedValue: 180_000,
        normalizedWeightPercent: 18,
        earnedNormalizedValue: 81_000,
        remainingNormalizedValue: 99_000,
      },
      {
        taskId: "recent-task",
        taskName: "Concluida recente",
        outlineNumber: "1.3",
        disciplineName: "Civil",
        progressPercentUsed: 100,
        progressSource: "percentComplete",
        normalizedValue: 120_000,
        normalizedWeightPercent: 12,
        earnedNormalizedValue: 120_000,
        remainingNormalizedValue: 0,
      },
      {
        taskId: "soon-task",
        taskName: "Comeca em breve",
        outlineNumber: "1.4",
        disciplineName: "Civil",
        progressPercentUsed: 0,
        progressSource: "none",
        normalizedValue: 110_000,
        normalizedWeightPercent: 11,
        earnedNormalizedValue: 0,
        remainingNormalizedValue: 110_000,
      },
      {
        taskId: "next-front-task",
        taskName: "Mecanica inicial",
        outlineNumber: "2.1",
        disciplineName: "Mecanica",
        progressPercentUsed: 0,
        progressSource: "none",
        normalizedValue: 150_000,
        normalizedWeightPercent: 15,
        earnedNormalizedValue: 0,
        remainingNormalizedValue: 150_000,
      },
      {
        taskId: "future-task",
        taskName: "Futuro distante",
        outlineNumber: "1.5",
        disciplineName: "Civil",
        progressPercentUsed: 0,
        progressSource: "none",
        normalizedValue: 250_000,
        normalizedWeightPercent: 25,
        earnedNormalizedValue: 0,
        remainingNormalizedValue: 250_000,
      },
      {
        taskId: "far-front-near-task",
        taskName: "Teste precoce",
        outlineNumber: "4.1",
        disciplineName: "Testes",
        progressPercentUsed: 0,
        progressSource: "none",
        normalizedValue: 210_000,
        normalizedWeightPercent: 21,
        earnedNormalizedValue: 0,
        remainingNormalizedValue: 210_000,
      },
      {
        taskId: "old-complete-task",
        taskName: "Concluida antiga",
        outlineNumber: "1.6",
        disciplineName: "Civil",
        progressPercentUsed: 100,
        progressSource: "percentComplete",
        normalizedValue: 140_000,
        normalizedWeightPercent: 14,
        earnedNormalizedValue: 140_000,
        remainingNormalizedValue: 0,
      },
    ],
    disciplineWeights: [],
    topTasksByRemainingValue: [],
    topDisciplinesByRemainingValue: [],
    disclaimer: "x",
  };
}

describe("buildOperationalTaskViews", () => {
  it("keeps overdue, current and upcoming impactful tasks while excluding low-impact noise, distant future and stale completed tasks", () => {
    const result = buildOperationalTaskViews(
      createWeightModel(),
      createProject(),
      "2026-03-26T10:00:00.000Z",
      10,
    );

    expect(result.map((task) => task.taskId)).toEqual([
      "late-task",
      "current-task",
      "next-front-task",
      "soon-task",
    ]);
  });

  it("preserves sorting by most negative gap first and then by impact", () => {
    const result = buildOperationalTaskViews(
      createWeightModel(),
      createProject(),
      "2026-03-26T10:00:00.000Z",
      10,
    );

    expect(result[0]).toMatchObject({
      taskId: "late-task",
      expectedPercent: 100,
      realPercent: 20,
      gapPercent: -80,
      impactPercent: 16,
    });
    expect(result[1]).toMatchObject({
      taskId: "current-task",
      impactPercent: 9.9,
    });
    expect(result).not.toEqual(
      expect.arrayContaining([expect.objectContaining({ taskId: "far-front-near-task" })]),
    );
  });

  it("calculates top impact percent from the filtered visible list", () => {
    const result = buildOperationalTaskViews(
      createWeightModel(),
      createProject(),
      "2026-03-26T10:00:00.000Z",
      10,
    );

    expect(calculateTopImpactPercent(result, 3)).toBe(40.9);
  });
});
